name: Auto Release
on: 
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  pack:
    runs-on: ubuntu-latest
    name: Auto Release

    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Make Release
        id: make_release
        run: python Packer.py

      - name: Get Current Time
        id: time
        run: echo "::set-output name=value::$(date '+%Y%m%d%H%M%S')"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.time.outputs.value }}
          release_name: AutoRelease-${{ steps.time.outputs.value }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: temp/Minecraft-Mod-Language-Package-Not-Included-Language-Package.zip
          asset_name: Minecraft-Mod-Language-Package-Not-Included-Language-Package.zip
          asset_content_type: application/zip
